export default [
"Darth Vader",
"Joker",
"Hannibal Lecter",
"Terminator",
"Magneto",
"Agent Smith",
"Lord Voldemort",
"Palpatine",
"Scar",
"Jack Torrance",
"Freddy Krueger",
"Loki",
"Hans Gruber",
"Michael Myers",
"Xenomorph (Alien)",
"Sauron",
"Bane",
"Thanos",
"Yautja",
"Anton Chigurh",
"T-1000",
"Pennywise the Dancing Clown",
"Norman Bates",
"Jason Voorhees",
"Hans Landa",
"John Doe",
"Darth Maul",
"Wicked Witch of the West",
"Davy Jones",
"Jigsaw",
"Gollum",
"Bellatrix Lestrange",
"Saruman",
"HAL 9000",
"Khan",
"Annie Wilkes",
"Nurse Ratched",
"Vito Corleone",
"Boba Fett",
"Jafar",
"Amon Goeth",
"Ra's al Ghul",
"Maleficent",
"Dolores Umbridge",
"Patrick Bateman",
"Buffalo Bill",
"Michael Corleone",
"Cruella de Vil",
"Jabba the Hutt",
"Harvey Dent",
"Scarecrow",
"Dr. Evil",
"Alex Delarge",
"Count Dracula",
"Count Dooku",
"Tommy DeVito",
"Captain Hook",
"Leatherface",
"Ultron",
"Tyler Durden",
"Commodus",
"President Snow",
"Pinhead",
"Biff Tannen",
"Professor Moriarty",
"The Penguin",
"Ghostface",
"Doctor Octopus",
"Chucky",
"Hades",
]
